version: "3.9"
services:
  db:
    container_name: MySQL
    platform: linux/amd64
    ports: 
      - 3306
    build: 
      context: .
      dockerfile: Docker/mysql/Dockerfile
    #Docker ボリューム mysql_data に /var/lib/mysql のデータが保存され、コンテナを削除してもデータが保持される
    volumes: 
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=shopping_remind_app
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
    healthcheck:
    # pingでmysqlにアクセスできるか見ている
      test: [
        "CMD-SHELL",
        "mysqladmin ping -h localhost -u ${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1",
        ]
      # testを実行する間隔を指定
      interval: 10s
      # テストコマンドがタイムアウトするまでの時間を指定
      timeout: 5s
      # testが失敗した場合に再試行する回数を指定
      retries: 5

  app:
    container_name: Django
    build:
      context: .
      dockerfile: Docker/Django/Dockerfile
     # volumes: ./src:/app/src
    #  追加
    volumes:
      - ./remindapp:/app/remindapp # プロジェクト全体をマウント　→以前の記述- ./remindapp/templates:/app/remindapp/templates
      #- ./remindapp/static:/app/remindapp/static 
    ports: 
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

# mysql_data という Docker Volumeを作成 →　他のコンテナで下記Volumeが利用できるようになる。
volumes:
    mysql_data:
      

