# Generated by Django 3.2 on 2025-02-19 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='defaultgoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='mygoods',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=36)),
                ('goods_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('日用品', '日用品'), ('食料', '食料'), ('その他', 'その他')], max_length=255)),
                ('purchase_date', models.DateTimeField()),
                ('next_purchase_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('next_purchase_term', models.CharField(max_length=255)),
                ('first_term', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RemindModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mailaddress', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8, message='パスワードは8文字以上で入力してください。')])),
                ('default_term', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.Group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permission_set', to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
